/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";

export function Model({ cilindro }) {
  const meshRef = useRef();

  const textures = useTexture({
    map: "/texturaCaja-three.jpg",
  });

  const material = useMemo(
    () =>
      new THREE.MeshStandardMaterial({
        map: textures.map,
      }),
    [textures.map]
  );

  // Animación opcional para simular el brillo del bombillo
  useFrame(() => {
    if (meshRef.current) {
      // Puedes agregar una animación aquí si deseas que la emisión "brille"
      // Ejemplo: meshRef.current.rotation.y += 0.01;
    }
  });

  const { nodes, materials } = useGLTF("/cajaNavidad.glb");
  return (
    <group
      ref={cilindro}
      rotation={[0, 3, 0]}
      position={[0, 0.009, 0]}
      dispose={null}
    >
      <mesh
        name="23112023007"
        castShadow
        receiveShadow
        geometry={nodes["23112023007"].geometry}
        material={materials.MADERA_Nogal}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023001"
        castShadow
        receiveShadow
        geometry={nodes["23112023001"].geometry}
        material={materials.MADERA_Nogal}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023002"
        castShadow
        receiveShadow
        geometry={nodes["23112023002"].geometry}
        material={materials.PLASTICO}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023004"
        castShadow
        receiveShadow
        geometry={nodes["23112023004"].geometry}
        material={materials.cintas}
        position={[0, 0, 0.162]}
        scale={0.133}
      />

      <mesh
        ref={meshRef}
        castShadow
        receiveShadow
        geometry={nodes["23112023005"].geometry}
        position={[0, 0, 0.162]}
        scale={0.133}
      >
        <meshStandardMaterial
          attach="material"
          color="#FFFFFF" // Color base del material (blanco)
          emissive="#FFFFFF" // Color de la emisión (blanco)
          emissiveIntensity={1} // Intensidad de la emisión
        />
      </mesh>
      <mesh
        name="23112023006"
        castShadow
        receiveShadow
        geometry={nodes["23112023006"].geometry}
        material={materials.carton_naranja}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023008"
        castShadow
        receiveShadow
        geometry={nodes["23112023008"].geometry}
        material={materials.carton}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023010"
        castShadow
        receiveShadow
        geometry={nodes["23112023010"].geometry}
        material={materials["Acero,_al_carbono"]}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023011"
        castShadow
        receiveShadow
        geometry={nodes["23112023011"].geometry}
        material={materials.Aire_MURO}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023012"
        castShadow
        receiveShadow
        geometry={nodes["23112023012"].geometry}
        material={materials.Muro_por_defecto}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023013"
        castShadow
        receiveShadow
        geometry={nodes["23112023013"].geometry}
        material={materials.MADERA}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023014"
        castShadow
        receiveShadow
        geometry={nodes["23112023014"].geometry}
        material={materials.Tela}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023017"
        castShadow
        receiveShadow
        geometry={nodes["23112023017"].geometry}
        material={materials["Madera_-_Castaño"]}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023018"
        castShadow
        receiveShadow
        geometry={nodes["23112023018"].geometry}
        material={materials.Cinta_Led_Amarilla}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
      <mesh
        name="23112023019"
        castShadow
        receiveShadow
        geometry={nodes["23112023019"].geometry}
        material={materials.Madera_de_perfiles}
        position={[0, 0, 0.162]}
        scale={0.133}
      />
    </group>
  );
}

useGLTF.preload("/cajaNavidad.glb");
